<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CreationsForge.Engine\CreationsForge.Engine.csproj" />
    <ProjectReference Include="..\CreationsForge.Fallout4\CreationsForge.Fallout4.csproj" />
    <ProjectReference Include="..\CreationsForge.Mcp\CreationsForge.Mcp.csproj" />
    <ProjectReference Include="..\CreationsForge.Skyrim\CreationsForge.Skyrim.csproj" />
    <ProjectReference Include="..\CreationsForge.Starfield\CreationsForge.Starfield.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
