// <auto-generated>
// Generated from Mutagen.Bethesda.Starfield 0.55.0-alpha.48 FieldIndex and getter metadata.
// Run: dotnet run --project Tools/CreationsForge.RecordFieldGenerator/CreationsForge.RecordFieldGenerator.csproj -- generate .
// Do not hand-edit generated visitor files.
// </auto-generated>
#nullable enable
using System.Text.Json;
using CreationsForge.Core.Engine.Contracts;
using CreationsForge.Core.Engine.RecordInspection;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Assets;
using Mutagen.Bethesda.Strings;
using Noggog;

namespace CreationsForge.Starfield.PluginAdapter.RecordInspection;

/// <content>Contains Starfield-specific leaf shapes that are outside the shared Mutagen scalar helpers.</content>
internal static partial class StarfieldNestedFieldCodec
{
    /// <summary>The explicit package-scoped namespace used by every generated Mutagen discriminator.</summary>
    internal const string RecordTypeNamespace = "Mutagen.Bethesda.Starfield/0.55.0-alpha.48:";

    /// <summary>Writes a canonical generated Mutagen type discriminator.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="recordTypeName">The concrete Mutagen type name without an assembly-qualified identity.</param>
    private static void WriteType(Utf8JsonWriter writer, string recordTypeName)
    {
        writer.WriteString("$type", RecordTypeNamespace + recordTypeName);
    }

    /// <summary>Writes a typed record link wrapper without flattening null-link state or canonical FormKey identity.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="value">The record link getter, or null.</param>
    /// <param name="wrapperType">The statically generated closed wrapper identity.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    private static void WriteFormLink(Utf8JsonWriter writer, IFormLinkGetter? value, string wrapperType, RecordJsonWriteContext? context)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        writer.WriteStartObject();
        WriteType(writer, wrapperType);
        writer.WriteBoolean("isNull", value.IsNull);
        writer.WritePropertyName("formKey");
        RecordJsonLeafWriter.WriteFormKey(writer, value.FormKeyNullable, context);
        writer.WriteEndObject();
    }

    /// <summary>Writes a typed record asset-link wrapper with supplied and normalized paths.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="value">The record asset-link getter, or null.</param>
    /// <param name="wrapperType">The statically generated closed wrapper identity.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    private static void WriteAssetLink(Utf8JsonWriter writer, IAssetLinkGetter? value, string wrapperType, RecordJsonWriteContext? context)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        writer.WriteStartObject();
        WriteType(writer, wrapperType);
        writer.WritePropertyName("value");
        RecordJsonLeafWriter.WriteAssetLink(writer, value, context);
        writer.WriteEndObject();
    }

    /// <summary>Writes a translated string wrapper with explicit Mutagen type and every available language entry.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="value">The translated string getter, or null.</param>
    /// <param name="cancellationToken">A token observed while enumerating translations.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    private static void WriteTranslatedString(Utf8JsonWriter writer, ITranslatedStringGetter? value, CancellationToken cancellationToken, RecordJsonWriteContext? context)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        writer.WriteStartObject();
        WriteType(writer, "Mutagen.Bethesda.Strings.ITranslatedStringGetter");
        writer.WritePropertyName("value");
        RecordJsonLeafWriter.WriteTranslatedString(writer, value, cancellationToken, context);
        writer.WriteEndObject();
    }

    /// <summary>Writes every semantic part of a Mutagen color value, including named-color state.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="value">The Mutagen color.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    private static void WriteColor(Utf8JsonWriter writer, System.Drawing.Color value, RecordJsonWriteContext? context)
    {
        writer.WriteStartObject();
        writer.WriteNumber("argb", value.ToArgb());
        writer.WriteNumber("a", value.A);
        writer.WriteNumber("r", value.R);
        writer.WriteNumber("g", value.G);
        writer.WriteNumber("b", value.B);
        writer.WriteBoolean("isEmpty", value.IsEmpty);
        writer.WriteBoolean("isKnownColor", value.IsKnownColor);
        writer.WriteBoolean("isNamedColor", value.IsNamedColor);
        writer.WriteBoolean("isSystemColor", value.IsSystemColor);
        writer.WritePropertyName("name");
        RecordJsonLeafWriter.WriteString(writer, value.Name, context);
        writer.WriteEndObject();
    }

    /// <summary>Adds one exact scalar-change descriptor.</summary>
    /// <param name="path">The stable record field path.</param>
    /// <param name="valuesEqual">Whether record values are exactly equal.</param>
    /// <param name="changes">The caller-owned ordered change collection.</param>
    /// <param name="cancellationToken">A token checked before adding a change.</param>
    private static void CompareValue(string path, bool valuesEqual, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)
    {
        RecordSemanticComparer.CompareValue(path, valuesEqual, changes, cancellationToken);
    }

    /// <summary>Adds one ordered collection change with exact positions.</summary>
    /// <param name="path">The stable Mutagen collection path.</param>
    /// <param name="kind">The ordered collection change kind.</param>
    /// <param name="beforePosition">The prior position, or null.</param>
    /// <param name="afterPosition">The resulting position, or null.</param>
    /// <param name="changes">The caller-owned ordered change collection.</param>
    /// <param name="cancellationToken">A token checked before adding a change.</param>
    private static void AddCollectionChange(string path, SemanticChangeKind kind, int? beforePosition, int? afterPosition, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        changes.Add(new SemanticChangeDescriptor(path, kind, beforePosition, afterPosition));
    }
}
