// <auto-generated>
// Generated from Mutagen.Bethesda.Starfield 0.55.0-alpha.53 FieldIndex and getter metadata.
// Run: dotnet run --project Tools/CreationsForge.RecordFieldGenerator/CreationsForge.RecordFieldGenerator.csproj -- generate .
// Do not hand-edit generated visitor files.
// </auto-generated>
#nullable enable
using System.Text.Json;
using CreationsForge.Core.Engine.Contracts;
using CreationsForge.Core.Engine.RecordInspection;
using Mutagen.Bethesda.Starfield;

namespace CreationsForge.Starfield.PluginAdapter.RecordInspection;

/// <summary>Writes and compares every indexed Starfield FormList component and condition descendant through static record getter access.</summary>
internal static partial class StarfieldNestedFieldCodec
{
    /// <summary>Writes one complete concrete Starfield component object in read-view mode, including its canonical package-scoped type discriminator.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="component">The concrete Mutagen component getter.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="writer"/> or <paramref name="component"/> is null.</exception>
    /// <exception cref="NotSupportedException">Thrown when the installed package supplies an ungenerated concrete component type.</exception>
    internal static void WriteComponent(Utf8JsonWriter writer, IAComponentGetter component, CancellationToken cancellationToken)
    {
        WriteComponent(writer, component, cancellationToken, null);
    }

    /// <summary>Writes one complete concrete Starfield component object using the requested per-call JSON mode.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="component">The concrete Mutagen component getter.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="writer"/> or <paramref name="component"/> is null.</exception>
    /// <exception cref="NotSupportedException">Thrown when the installed package supplies an ungenerated concrete component type.</exception>
    internal static void WriteComponent(Utf8JsonWriter writer, IAComponentGetter component, CancellationToken cancellationToken, RecordJsonWriteContext? context)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(component);
        cancellationToken.ThrowIfCancellationRequested();
        WritePolymorphicAComponent(writer, component, cancellationToken, context);
    }

    /// <summary>Compares all fields of two concrete Starfield components in Mutagen FieldIndex order.</summary>
    /// <param name="before">The prior component, or null.</param>
    /// <param name="after">The resulting component, or null.</param>
    /// <param name="path">The root-owned component path.</param>
    /// <param name="changes">The caller-owned ordered change collection.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    internal static void CompareComponent(IAComponentGetter? before, IAComponentGetter? after, string path, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)
    {
        ComparePolymorphicAComponent(before, after, path, changes, cancellationToken);
    }

    /// <summary>Writes one complete concrete Starfield condition object and its concrete condition-data graph in read-view mode.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="condition">The concrete Mutagen condition getter.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="writer"/> or <paramref name="condition"/> is null.</exception>
    /// <exception cref="NotSupportedException">Thrown when the installed package supplies an ungenerated concrete condition type.</exception>
    internal static void WriteCondition(Utf8JsonWriter writer, IConditionGetter condition, CancellationToken cancellationToken)
    {
        WriteCondition(writer, condition, cancellationToken, null);
    }

    /// <summary>Writes one complete concrete Starfield condition object and its concrete condition-data graph using the requested per-call JSON mode.</summary>
    /// <param name="writer">The caller-owned JSON writer.</param>
    /// <param name="condition">The concrete Mutagen condition getter.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    /// <param name="context">The per-call write mode and validation state, or null for read-view output.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="writer"/> or <paramref name="condition"/> is null.</exception>
    /// <exception cref="NotSupportedException">Thrown when the installed package supplies an ungenerated concrete condition type.</exception>
    internal static void WriteCondition(Utf8JsonWriter writer, IConditionGetter condition, CancellationToken cancellationToken, RecordJsonWriteContext? context)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(condition);
        cancellationToken.ThrowIfCancellationRequested();
        WritePolymorphicCondition(writer, condition, cancellationToken, context);
    }

    /// <summary>Compares all fields of two concrete Starfield conditions and their concrete condition-data graphs.</summary>
    /// <param name="before">The prior condition, or null.</param>
    /// <param name="after">The resulting condition, or null.</param>
    /// <param name="path">The root-owned condition path.</param>
    /// <param name="changes">The caller-owned ordered change collection.</param>
    /// <param name="cancellationToken">A token observed throughout nested traversal.</param>
    internal static void CompareCondition(IConditionGetter? before, IConditionGetter? after, string path, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)
    {
        ComparePolymorphicCondition(before, after, path, changes, cancellationToken);
    }
}
