// <auto-generated>
// Generated from Mutagen.Bethesda.Starfield 0.55.0-alpha.48 FieldIndex and getter metadata.
// Run: dotnet run --project Tools/CreationsForge.NativeFieldGenerator/CreationsForge.NativeFieldGenerator.csproj -- generate .
// Do not hand-edit generated visitor files.
// </auto-generated>
#nullable enable
using CreationsForge.Core.Engine.NativeWire;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Strings;
using Noggog;

namespace CreationsForge.Starfield.Native.NativeInspection;

/// <content>Contains closed Starfield reader leaf shapes and derived-value validation.</content>
internal static partial class StarfieldNestedFieldCodec
{
    /// <summary>Defines a closed two-dimensional native array value.</summary>
    private static readonly NativeWireObjectShape Array2dReadShape = new("Array2d", new[] { "width", "height", "rows" });

    /// <summary>Defines a closed two-dimensional float vector.</summary>
    private static readonly NativeWireObjectShape P2FloatReadShape = new("P2Float", new[] { "X", "Y" });

    /// <summary>Defines a closed two-dimensional integer vector.</summary>
    private static readonly NativeWireObjectShape P2IntReadShape = new("P2Int", new[] { "X", "Y" });

    /// <summary>Defines a closed three-dimensional float vector.</summary>
    private static readonly NativeWireObjectShape P3FloatReadShape = new("P3Float", new[] { "X", "Y", "Z" });

    /// <summary>Defines the complete redundant native color representation.</summary>
    private static readonly NativeWireObjectShape ColorReadShape = new("Color", new[] { "argb", "a", "r", "g", "b", "isEmpty", "isKnownColor", "isNamedColor", "isSystemColor", "name" });

    /// <summary>Defines a typed ordinary or nullable FormKey link wrapper.</summary>
    private static readonly NativeWireObjectShape FormLinkReadShape = new("FormLink", new[] { "$type", "isNull", "formKey" });

    /// <summary>Defines an owner-sensitive link-or-index wrapper.</summary>
    private static readonly NativeWireObjectShape FormLinkOrIndexReadShape = new("FormLinkOrIndex", new[] { "$type", "index", "link" }, new[] { "usesLink", "usesAlias", "usesPackageData" });

    /// <summary>Defines a typed asset-link wrapper.</summary>
    private static readonly NativeWireObjectShape AssetLinkReadShape = new("AssetLink", new[] { "$type", "value" });

    /// <summary>Defines the redundant asset-link path payload.</summary>
    private static readonly NativeWireObjectShape AssetLinkValueReadShape = new("asset-link value", new[] { "isNull", "givenPath" }, new[] { "dataRelativePath", "extension" });

    /// <summary>Defines a translated-string wrapper.</summary>
    private static readonly NativeWireObjectShape TranslatedStringReadShape = new("TranslatedString", new[] { "$type", "value" });

    /// <summary>Defines a complete translated-string payload.</summary>
    private static readonly NativeWireObjectShape TranslatedStringValueReadShape = new("translated-string value", new[] { "targetLanguage", "value", "translations" });

    /// <summary>Defines one translated-string language entry.</summary>
    private static readonly NativeWireObjectShape TranslationEntryReadShape = new("translation entry", new[] { "language", "value" });

    /// <summary>Validates one package-scoped wire discriminator against the statically selected native type.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned discriminator value.</param>
    /// <param name="nativeTypeName">The expected native full name without package scope.</param>
    private static void ReadAndValidateType(NativeWireReadContext context, NativeWireValue value, string nativeTypeName)
    {
        var actual = context.ReadString(value);
        var expected = NativeTypeNamespace + nativeTypeName;
        if (!string.Equals(actual, expected, StringComparison.Ordinal))
        {
            context.Reject(value, $"Expected native type discriminator '{expected}'.");
        }
    }

    /// <summary>Rejects one invalid generated value while satisfying an expression return contract.</summary>
    /// <typeparam name="T">The expression result type that is never produced.</typeparam>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned invalid value.</param>
    /// <param name="message">The invariant failure description.</param>
    /// <returns>This method never returns.</returns>
    private static T RejectValue<T>(NativeWireReadContext context, NativeWireValue value, string message)
    {
        context.Reject(value, message);
        throw new InvalidOperationException("NativeWireReadContext.Reject unexpectedly returned.");
    }

    /// <summary>Reads a nullable native string from an explicitly present required property.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned string or null value.</param>
    /// <returns>The decoded string or null.</returns>
    private static string? ReadNullableString(NativeWireReadContext context, NativeWireValue value)
    {
        return context.IsNull(value) ? null : context.ReadString(value);
    }

    /// <summary>Reads a nullable FormKey while validating the complete typed wrapper state.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned link wrapper.</param>
    /// <param name="expectedWrapperType">The exact generated getter wrapper identity.</param>
    /// <returns>The decoded FormKey, or null for the native null-link state.</returns>
    private static FormKey? ReadFormLinkKey(NativeWireReadContext context, NativeWireValue value, string expectedWrapperType)
    {
        var container = context.ReadObject(value, FormLinkReadShape);
        ReadAndValidateType(context, container.GetRequiredProperty("$type"), expectedWrapperType);
        var isNullValue = container.GetRequiredProperty("isNull");
        var isNull = context.ReadBoolean(isNullValue);
        var formKeyValue = container.GetRequiredProperty("formKey");
        var formKey = context.IsNull(formKeyValue) ? (FormKey?)null : context.ReadFormKey(formKeyValue);
        if (isNull != (!formKey.HasValue || formKey.Value.IsNull))
        {
            context.Reject(isNullValue, "Form-link null state does not match its FormKey.");
        }
        return formKey;
    }

    /// <summary>Reads the owner-independent data of one link-or-index wrapper for later owner-bound construction.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned link-or-index wrapper.</param>
    /// <param name="expectedWrapperType">The exact generated link-or-index getter identity.</param>
    /// <param name="expectedLinkType">The exact generated nested link getter identity.</param>
    /// <returns>The complete owner-independent mode, index, and link data.</returns>
    private static (bool? UsesLink, NativeWireValue? UsesLinkValue, bool? UsesAlias, NativeWireValue? UsesAliasValue, bool? UsesPackageData, NativeWireValue? UsesPackageDataValue, uint? Index, FormKey? Link) ReadFormLinkOrIndex(NativeWireReadContext context, NativeWireValue value, string expectedWrapperType, string expectedLinkType)
    {
        var container = context.ReadObject(value, FormLinkOrIndexReadShape);
        ReadAndValidateType(context, container.GetRequiredProperty("$type"), expectedWrapperType);
        var hasUsesLink = container.TryGetOptionalProperty("usesLink", out var usesLinkValue);
        var usesLink = hasUsesLink ? context.ReadBoolean(usesLinkValue) : (bool?)null;
        var hasUsesAlias = container.TryGetOptionalProperty("usesAlias", out var usesAliasValue);
        var usesAlias = hasUsesAlias ? context.ReadBoolean(usesAliasValue) : (bool?)null;
        var hasUsesPackageData = container.TryGetOptionalProperty("usesPackageData", out var usesPackageDataValue);
        var usesPackageData = hasUsesPackageData ? context.ReadBoolean(usesPackageDataValue) : (bool?)null;
        var indexValue = container.GetRequiredProperty("index");
        var index = context.IsNull(indexValue) ? (uint?)null : context.ReadUInt32(indexValue);
        var link = ReadFormLinkKey(context, container.GetRequiredProperty("link"), expectedLinkType);
        return (usesLink, hasUsesLink ? usesLinkValue : null, usesAlias, hasUsesAlias ? usesAliasValue : null, usesPackageData, hasUsesPackageData ? usesPackageDataValue : null, index, link);
    }

    /// <summary>Reads one complete typed asset-link wrapper without treating normalized paths as construction authority.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned asset-link wrapper.</param>
    /// <param name="expectedWrapperType">The exact generated asset-link getter identity.</param>
    /// <returns>The supplied path and redundant derived path state.</returns>
    private static (bool IsNull, NativeWireValue IsNullValue, string GivenPath, NativeWireValue GivenPathValue, string? DataRelativePath, NativeWireValue? DataRelativePathValue, string? Extension, NativeWireValue? ExtensionValue) ReadAssetLink(NativeWireReadContext context, NativeWireValue value, string expectedWrapperType)
    {
        var container = context.ReadObject(value, AssetLinkReadShape);
        ReadAndValidateType(context, container.GetRequiredProperty("$type"), expectedWrapperType);
        var payload = context.ReadObject(container.GetRequiredProperty("value"), AssetLinkValueReadShape);
        var isNullValue = payload.GetRequiredProperty("isNull");
        var isNull = context.ReadBoolean(isNullValue);
        var givenPathValue = payload.GetRequiredProperty("givenPath");
        var givenPath = context.ReadString(givenPathValue);
        var hasDataRelativePath = payload.TryGetOptionalProperty("dataRelativePath", out var dataRelativePathValue);
        var dataRelativePath = hasDataRelativePath ? context.ReadString(dataRelativePathValue) : null;
        var hasExtension = payload.TryGetOptionalProperty("extension", out var extensionValue);
        var extension = hasExtension ? context.ReadString(extensionValue) : null;
        return (isNull, isNullValue, givenPath, givenPathValue, dataRelativePath, hasDataRelativePath ? dataRelativePathValue : null, extension, hasExtension ? extensionValue : null);
    }

    /// <summary>Reads a translated string and verifies its redundant target-language value.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned translated-string wrapper.</param>
    /// <returns>The fully populated mutable translated string.</returns>
    private static TranslatedString ReadTranslatedString(NativeWireReadContext context, NativeWireValue value)
    {
        var container = context.ReadObject(value, TranslatedStringReadShape);
        ReadAndValidateType(context, container.GetRequiredProperty("$type"), "Mutagen.Bethesda.Strings.ITranslatedStringGetter");
        var payload = context.ReadObject(container.GetRequiredProperty("value"), TranslatedStringValueReadShape);
        var targetLanguageValue = payload.GetRequiredProperty("targetLanguage");
        var targetLanguage = ReadNamedEnum<Language>(context, targetLanguageValue);
        var expectedValue = ReadNullableString(context, payload.GetRequiredProperty("value"));
        var translationsValue = payload.GetRequiredProperty("translations");
        var translations = context.ReadArray(translationsValue);
        var result = new TranslatedString(targetLanguage);
        var seen = new HashSet<Language>();
        for (var index = 0; index < translations.Count; index++)
        {
            var entryValue = translations.GetElement(index);
            var entry = context.ReadObject(entryValue, TranslationEntryReadShape);
            var languageValue = entry.GetRequiredProperty("language");
            var language = ReadNamedEnum<Language>(context, languageValue);
            if (!seen.Add(language))
            {
                context.Reject(languageValue, "Translation language occurs more than once.");
            }
            result.Set(language, context.ReadString(entry.GetRequiredProperty("value")));
        }
        if (!string.Equals(result.String, expectedValue, StringComparison.Ordinal))
        {
            context.Reject(value, "Translated-string target value does not match its language entries.");
        }
        return result;
    }

    /// <summary>Reads one exact symbolic enum name and rejects aliases or numeric spellings.</summary>
    /// <typeparam name="TEnum">The enum selected by generated code.</typeparam>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned enum-name string.</param>
    /// <returns>The exact defined enum value.</returns>
    private static TEnum ReadNamedEnum<TEnum>(NativeWireReadContext context, NativeWireValue value) where TEnum : struct, Enum
    {
        var text = context.ReadString(value);
        if (!Enum.TryParse<TEnum>(text, false, out var result) || !Enum.IsDefined(result) || !string.Equals(result.ToString(), text, StringComparison.Ordinal))
        {
            context.Reject(value, $"Expected a canonical {typeof(TEnum).Name} name.");
        }
        return result;
    }

    /// <summary>Reads a two-dimensional floating-point vector.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned vector object.</param>
    /// <returns>The exact native vector.</returns>
    private static P2Float ReadP2Float(NativeWireReadContext context, NativeWireValue value)
    {
        var container = context.ReadObject(value, P2FloatReadShape);
        return new P2Float(context.ReadSingle(container.GetRequiredProperty("X")), context.ReadSingle(container.GetRequiredProperty("Y")));
    }

    /// <summary>Reads a two-dimensional integer vector.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned vector object.</param>
    /// <returns>The exact native vector.</returns>
    private static P2Int ReadP2Int(NativeWireReadContext context, NativeWireValue value)
    {
        var container = context.ReadObject(value, P2IntReadShape);
        return new P2Int(context.ReadInt32(container.GetRequiredProperty("X")), context.ReadInt32(container.GetRequiredProperty("Y")));
    }

    /// <summary>Reads a three-dimensional floating-point vector.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned vector object.</param>
    /// <returns>The exact native vector.</returns>
    private static P3Float ReadP3Float(NativeWireReadContext context, NativeWireValue value)
    {
        var container = context.ReadObject(value, P3FloatReadShape);
        return new P3Float(context.ReadSingle(container.GetRequiredProperty("X")), context.ReadSingle(container.GetRequiredProperty("Y")), context.ReadSingle(container.GetRequiredProperty("Z")));
    }

    /// <summary>Reads one complete native color and validates every redundant representation field.</summary>
    /// <param name="context">The request-local bounded read context.</param>
    /// <param name="value">The context-owned color object.</param>
    /// <returns>The exact reconstructible native color.</returns>
    private static System.Drawing.Color ReadColor(NativeWireReadContext context, NativeWireValue value)
    {
        var container = context.ReadObject(value, ColorReadShape);
        var argb = context.ReadInt32(container.GetRequiredProperty("argb"));
        var a = context.ReadByte(container.GetRequiredProperty("a"));
        var r = context.ReadByte(container.GetRequiredProperty("r"));
        var g = context.ReadByte(container.GetRequiredProperty("g"));
        var b = context.ReadByte(container.GetRequiredProperty("b"));
        var isEmpty = context.ReadBoolean(container.GetRequiredProperty("isEmpty"));
        var isKnownColor = context.ReadBoolean(container.GetRequiredProperty("isKnownColor"));
        var isNamedColor = context.ReadBoolean(container.GetRequiredProperty("isNamedColor"));
        var isSystemColor = context.ReadBoolean(container.GetRequiredProperty("isSystemColor"));
        var nameValue = container.GetRequiredProperty("name");
        var name = context.ReadString(nameValue);
        System.Drawing.Color result;
        if (isEmpty)
        {
            result = System.Drawing.Color.Empty;
        }
        else if (isKnownColor || isSystemColor)
        {
            var knownColor = ReadNamedEnum<System.Drawing.KnownColor>(context, nameValue);
            result = System.Drawing.Color.FromKnownColor(knownColor);
        }
        else if (isNamedColor)
        {
            result = System.Drawing.Color.FromName(name);
        }
        else
        {
            result = System.Drawing.Color.FromArgb(argb);
        }
        if (result.ToArgb() != argb || result.A != a || result.R != r || result.G != g || result.B != b
            || result.IsEmpty != isEmpty || result.IsKnownColor != isKnownColor || result.IsNamedColor != isNamedColor
            || result.IsSystemColor != isSystemColor || !string.Equals(result.Name, name, StringComparison.Ordinal))
        {
            context.Reject(value, "Color metadata is not an exact reconstructible native color.");
        }
        return result;
    }
}
