ALTER TABLE Keyword ADD COLUMN Color TEXT NULL;
ALTER TABLE Keyword ADD COLUMN KeywordType TEXT NULL;
ALTER TABLE Keyword ADD COLUMN FNAM TEXT NULL;

CREATE INDEX IF NOT EXISTS IX_Keyword_KeywordType
ON Keyword(KeywordType);
