using System.Text;

namespace CreationsForge.RecordFieldGenerator;

/// <content>Emits the generated codec entrypoint and Starfield-local leaf source files.</content>
internal sealed partial class CodecEmitter
{
    /// <summary>
    /// Emits read-view and context-aware root writers plus the two comparison entrypoints owned by this nested visitor.
    /// </summary>
    /// <returns>Complete CRLF-normalized source text.</returns>
    private string EmitEntryPoints()
    {
        var output = SourceHeader();
        output.AppendLine("using System.Text.Json;");
        output.AppendLine("using CreationsForge.Core.Engine.Contracts;");
        output.AppendLine("using CreationsForge.Core.Engine.RecordInspection;");
        output.AppendLine("using Mutagen.Bethesda.Starfield;");
        output.AppendLine();
        output.AppendLine("namespace CreationsForge.Starfield.PluginAdapter.RecordInspection;");
        output.AppendLine();
        output.AppendLine("/// <summary>Writes and compares every indexed Starfield FormList component and condition descendant through static record getter access.</summary>");
        output.AppendLine("internal static partial class StarfieldNestedFieldCodec");
        output.AppendLine("{");
        output.AppendLine("    /// <summary>Writes one complete concrete Starfield component object in read-view mode, including its canonical package-scoped type discriminator.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"component\">The concrete Mutagen component getter.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"writer\"/> or <paramref name=\"component\"/> is null.</exception>");
        output.AppendLine("    /// <exception cref=\"NotSupportedException\">Thrown when the installed package supplies an ungenerated concrete component type.</exception>");
        output.AppendLine("    internal static void WriteComponent(Utf8JsonWriter writer, IAComponentGetter component, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        WriteComponent(writer, component, cancellationToken, null);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes one complete concrete Starfield component object using the requested per-call JSON mode.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"component\">The concrete Mutagen component getter.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"writer\"/> or <paramref name=\"component\"/> is null.</exception>");
        output.AppendLine("    /// <exception cref=\"NotSupportedException\">Thrown when the installed package supplies an ungenerated concrete component type.</exception>");
        output.AppendLine("    internal static void WriteComponent(Utf8JsonWriter writer, IAComponentGetter component, CancellationToken cancellationToken, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        output.AppendLine("        ArgumentNullException.ThrowIfNull(component);");
        output.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        output.AppendLine("        WritePolymorphicAComponent(writer, component, cancellationToken, context);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Compares all fields of two concrete Starfield components in Mutagen FieldIndex order.</summary>");
        output.AppendLine("    /// <param name=\"before\">The prior component, or null.</param>");
        output.AppendLine("    /// <param name=\"after\">The resulting component, or null.</param>");
        output.AppendLine("    /// <param name=\"path\">The root-owned component path.</param>");
        output.AppendLine("    /// <param name=\"changes\">The caller-owned ordered change collection.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    internal static void CompareComponent(IAComponentGetter? before, IAComponentGetter? after, string path, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        ComparePolymorphicAComponent(before, after, path, changes, cancellationToken);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes one complete concrete Starfield condition object and its concrete condition-data graph in read-view mode.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"condition\">The concrete Mutagen condition getter.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"writer\"/> or <paramref name=\"condition\"/> is null.</exception>");
        output.AppendLine("    /// <exception cref=\"NotSupportedException\">Thrown when the installed package supplies an ungenerated concrete condition type.</exception>");
        output.AppendLine("    internal static void WriteCondition(Utf8JsonWriter writer, IConditionGetter condition, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        WriteCondition(writer, condition, cancellationToken, null);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes one complete concrete Starfield condition object and its concrete condition-data graph using the requested per-call JSON mode.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"condition\">The concrete Mutagen condition getter.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"writer\"/> or <paramref name=\"condition\"/> is null.</exception>");
        output.AppendLine("    /// <exception cref=\"NotSupportedException\">Thrown when the installed package supplies an ungenerated concrete condition type.</exception>");
        output.AppendLine("    internal static void WriteCondition(Utf8JsonWriter writer, IConditionGetter condition, CancellationToken cancellationToken, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        ArgumentNullException.ThrowIfNull(writer);");
        output.AppendLine("        ArgumentNullException.ThrowIfNull(condition);");
        output.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        output.AppendLine("        WritePolymorphicCondition(writer, condition, cancellationToken, context);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Compares all fields of two concrete Starfield conditions and their concrete condition-data graphs.</summary>");
        output.AppendLine("    /// <param name=\"before\">The prior condition, or null.</param>");
        output.AppendLine("    /// <param name=\"after\">The resulting condition, or null.</param>");
        output.AppendLine("    /// <param name=\"path\">The root-owned condition path.</param>");
        output.AppendLine("    /// <param name=\"changes\">The caller-owned ordered change collection.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed throughout nested traversal.</param>");
        output.AppendLine("    internal static void CompareCondition(IConditionGetter? before, IConditionGetter? after, string path, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        ComparePolymorphicCondition(before, after, path, changes, cancellationToken);");
        output.AppendLine("    }");
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// Emits shared Starfield-local terminal writers and semantic collection helpers.
    /// </summary>
    /// <returns>Complete source text for local terminal operations.</returns>
    private static string EmitLeaves()
    {
        var output = SourceHeader();
        output.AppendLine("using System.Text.Json;");
        output.AppendLine("using CreationsForge.Core.Engine.Contracts;");
        output.AppendLine("using CreationsForge.Core.Engine.RecordInspection;");
        output.AppendLine("using Mutagen.Bethesda.Plugins;");
        output.AppendLine("using Mutagen.Bethesda.Plugins.Assets;");
        output.AppendLine("using Mutagen.Bethesda.Strings;");
        output.AppendLine("using Noggog;");
        output.AppendLine();
        output.AppendLine("namespace CreationsForge.Starfield.PluginAdapter.RecordInspection;");
        output.AppendLine();
        output.AppendLine("/// <content>Contains Starfield-specific leaf shapes that are outside the shared Mutagen scalar helpers.</content>");
        output.AppendLine("internal static partial class StarfieldNestedFieldCodec");
        output.AppendLine("{");
        output.AppendLine($"    /// <summary>The explicit package-scoped namespace used by every generated Mutagen discriminator.</summary>");
        output.AppendLine($"    internal const string RecordTypeNamespace = \"Mutagen.Bethesda.Starfield/{PackageVersion}:\";");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes a canonical generated Mutagen type discriminator.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"recordTypeName\">The concrete Mutagen type name without an assembly-qualified identity.</param>");
        output.AppendLine("    private static void WriteType(Utf8JsonWriter writer, string recordTypeName)");
        output.AppendLine("    {");
        output.AppendLine("        writer.WriteString(\"$type\", RecordTypeNamespace + recordTypeName);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes a typed record link wrapper without flattening null-link state or canonical FormKey identity.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"value\">The record link getter, or null.</param>");
        output.AppendLine("    /// <param name=\"wrapperType\">The statically generated closed wrapper identity.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    private static void WriteFormLink(Utf8JsonWriter writer, IFormLinkGetter? value, string wrapperType, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        if (value is null)");
        output.AppendLine("        {");
        output.AppendLine("            writer.WriteNullValue();");
        output.AppendLine("            return;");
        output.AppendLine("        }");
        output.AppendLine();
        output.AppendLine("        writer.WriteStartObject();");
        output.AppendLine("        WriteType(writer, wrapperType);");
        output.AppendLine("        writer.WriteBoolean(\"isNull\", value.IsNull);");
        output.AppendLine("        writer.WritePropertyName(\"formKey\");");
        output.AppendLine("        RecordJsonLeafWriter.WriteFormKey(writer, value.FormKeyNullable, context);");
        output.AppendLine("        writer.WriteEndObject();");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes a typed record asset-link wrapper with supplied and normalized paths.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"value\">The record asset-link getter, or null.</param>");
        output.AppendLine("    /// <param name=\"wrapperType\">The statically generated closed wrapper identity.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    private static void WriteAssetLink(Utf8JsonWriter writer, IAssetLinkGetter? value, string wrapperType, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        if (value is null)");
        output.AppendLine("        {");
        output.AppendLine("            writer.WriteNullValue();");
        output.AppendLine("            return;");
        output.AppendLine("        }");
        output.AppendLine();
        output.AppendLine("        writer.WriteStartObject();");
        output.AppendLine("        WriteType(writer, wrapperType);");
        output.AppendLine("        writer.WritePropertyName(\"value\");");
        output.AppendLine("        RecordJsonLeafWriter.WriteAssetLink(writer, value, context);");
        output.AppendLine("        writer.WriteEndObject();");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes a translated string wrapper with explicit Mutagen type and every available language entry.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"value\">The translated string getter, or null.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token observed while enumerating translations.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    private static void WriteTranslatedString(Utf8JsonWriter writer, ITranslatedStringGetter? value, CancellationToken cancellationToken, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        if (value is null)");
        output.AppendLine("        {");
        output.AppendLine("            writer.WriteNullValue();");
        output.AppendLine("            return;");
        output.AppendLine("        }");
        output.AppendLine();
        output.AppendLine("        writer.WriteStartObject();");
        output.AppendLine("        WriteType(writer, \"Mutagen.Bethesda.Strings.ITranslatedStringGetter\");");
        output.AppendLine("        writer.WritePropertyName(\"value\");");
        output.AppendLine("        RecordJsonLeafWriter.WriteTranslatedString(writer, value, cancellationToken, context);");
        output.AppendLine("        writer.WriteEndObject();");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Writes every semantic part of a Mutagen color value, including named-color state.</summary>");
        output.AppendLine("    /// <param name=\"writer\">The caller-owned JSON writer.</param>");
        output.AppendLine("    /// <param name=\"value\">The Mutagen color.</param>");
        output.AppendLine("    /// <param name=\"context\">The per-call write mode and validation state, or null for read-view output.</param>");
        output.AppendLine("    private static void WriteColor(Utf8JsonWriter writer, System.Drawing.Color value, RecordJsonWriteContext? context)");
        output.AppendLine("    {");
        output.AppendLine("        writer.WriteStartObject();");
        output.AppendLine("        writer.WriteNumber(\"argb\", value.ToArgb());");
        output.AppendLine("        writer.WriteNumber(\"a\", value.A);");
        output.AppendLine("        writer.WriteNumber(\"r\", value.R);");
        output.AppendLine("        writer.WriteNumber(\"g\", value.G);");
        output.AppendLine("        writer.WriteNumber(\"b\", value.B);");
        output.AppendLine("        writer.WriteBoolean(\"isEmpty\", value.IsEmpty);");
        output.AppendLine("        writer.WriteBoolean(\"isKnownColor\", value.IsKnownColor);");
        output.AppendLine("        writer.WriteBoolean(\"isNamedColor\", value.IsNamedColor);");
        output.AppendLine("        writer.WriteBoolean(\"isSystemColor\", value.IsSystemColor);");
        output.AppendLine("        writer.WritePropertyName(\"name\");");
        output.AppendLine("        RecordJsonLeafWriter.WriteString(writer, value.Name, context);");
        output.AppendLine("        writer.WriteEndObject();");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Adds one exact scalar-change descriptor.</summary>");
        output.AppendLine("    /// <param name=\"path\">The stable record field path.</param>");
        output.AppendLine("    /// <param name=\"valuesEqual\">Whether record values are exactly equal.</param>");
        output.AppendLine("    /// <param name=\"changes\">The caller-owned ordered change collection.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token checked before adding a change.</param>");
        output.AppendLine("    private static void CompareValue(string path, bool valuesEqual, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        RecordSemanticComparer.CompareValue(path, valuesEqual, changes, cancellationToken);");
        output.AppendLine("    }");
        output.AppendLine();
        output.AppendLine("    /// <summary>Adds one ordered collection change with exact positions.</summary>");
        output.AppendLine("    /// <param name=\"path\">The stable Mutagen collection path.</param>");
        output.AppendLine("    /// <param name=\"kind\">The ordered collection change kind.</param>");
        output.AppendLine("    /// <param name=\"beforePosition\">The prior position, or null.</param>");
        output.AppendLine("    /// <param name=\"afterPosition\">The resulting position, or null.</param>");
        output.AppendLine("    /// <param name=\"changes\">The caller-owned ordered change collection.</param>");
        output.AppendLine("    /// <param name=\"cancellationToken\">A token checked before adding a change.</param>");
        output.AppendLine("    private static void AddCollectionChange(string path, SemanticChangeKind kind, int? beforePosition, int? afterPosition, ICollection<SemanticChangeDescriptor> changes, CancellationToken cancellationToken)");
        output.AppendLine("    {");
        output.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        output.AppendLine("        changes.Add(new SemanticChangeDescriptor(path, kind, beforePosition, afterPosition));");
        output.AppendLine("    }");
        output.AppendLine("}");
        return output.ToString();
    }
}
