name: Validate Pull Request

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: .NET SDK version to install.
        required: false
        type: string
        default: '10.0.x'
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

env:
  DOTNET_VERSION: ${{ inputs.dotnet-version || '10.0.x' }}
  AVALONIA_UI_LICENSE_KEY: ${{ secrets.AVALONIA_UI_LICENSE_KEY }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        shell: pwsh
        run: dotnet restore ./CreationsForge.sln

      - name: Build
        shell: pwsh
        run: dotnet build ./CreationsForge.sln --configuration Release --no-restore

      - name: Unit Tests
        shell: pwsh
        run: dotnet test ./CreationsForge.UnitTests/CreationsForge.UnitTests.csproj --configuration Release --no-build --filter "Category!=RequiresStarfield"

    # With the new avalonia headless tests this is randomly hanging on GitHub's Runners
    #   - name: Presentation Layer Tests
    #     shell: pwsh
    #     run: dotnet test ./CreationsForge.PresentationTests/CreationsForge.PresentationTests.csproj --configuration Release --no-build --filter "Category!=RequiresStarfield"
